volumes:
  postgres:
  pgadmin:

services:
  postgres17:
    container_name: postgres17
    image: 'postgres:17-alpine3.20'
    environment:
      POSTGRES_DB: jwt
      POSTGRES_USER: hendisantika
      POSTGRES_PASSWORD: 53cret
    volumes:
      - ./postgres17:/data/postgres
    ports:
      - '5432'
    restart: unless-stopped

  pgadmin8:
    container_name: pgadmin
    image: 'dpage/pgadmin4:8.12.0'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - '5050:5050'
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:hendisantika:53cret' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
